grpc:
    port: 0
    enableReflection: true

spring: 
  application:
    name: fm-rabbitmq-kafka-connector
  cloud:
    service-registry:
      auto-registration:
        enabled: false
    consul:
      discovery:
        enabled: true
        heartbeat: 
          enabled: true
        register: false
        hostname: ${spring.cloud.client.ip-address}
      host: 192.168.8.6
      port: 8500
      enabled: true