/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fm.rabbitmq.kafka.connector;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


@SpringBootApplication
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        var ctx = SpringApplication.run(App.class, args);
        System.out.println("Applcaition started ....");
       // SpringApplication.exit(ctx); 
    }
}
