/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fm.rabbitmq.kafka.connector;

import java.util.Arrays;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.consul.serviceregistry.ConsulServiceRegistry;
import org.springframework.context.annotation.Bean;

import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;
import io.grpc.examples.GreeterGrpc;
import io.grpc.examples.GreeterOuterClass.HelloReply;
import io.grpc.examples.GreeterOuterClass.HelloRequest;

@SpringBootApplication
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
        System.out.println("Applcaition started ....");
    }
    @Bean
    public GrpcServiceConsulRegistrar consulRegistrarTest(ConsulServiceRegistry consulServiceRegistry){
        return new GrpcServiceConsulRegistrar(consulServiceRegistry);
    }
}
